[versions]
agp = "8.13.0"
composeBom = "2025.10.01"
kotlin = "2.2.21"
kotlinBomVersion = "2.2.21"
coreKtx = "1.17.0"
coilVersion = "2.2.2"
crashreport = "4.1.9.3"
glanceAppwidget = "1.1.1"
gson = "2.11.0"
hiltAndroidCompilerVersion = "2.57.2"
hiltAndroidVersion = "2.57.2"
hiltNavigationComposeVersion = "1.2.0"
jsoup = "1.19.1"
activityCompose = "1.11.0"
loggingInterceptorVersion = "5.1.0"
mmkvStatic = "2.2.2"
monetVersion = "0.1.0-alpha03"
navigationCompose = "2.9.0"
persistentcookiejar = "v1.0.1"
retrofitVersion = "2.11.0"
zxingAndroidEmbeddedVersion = "4.3.0"
adsMobileSdkVersion = "0.18.0-beta01"
kyant0Capsule = "2.1.1"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-ui = { module = "androidx.compose.ui:ui" }
coil = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBomVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
material3 = { module = "androidx.compose.material3:material3" }
mmkv-static = { module = "com.tencent:mmkv-static", version.ref = "mmkvStatic" }
monet = { module = "com.github.Kyant0:Monet", version.ref = "monetVersion" }
persistentcookiejar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentcookiejar" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbeddedVersion" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdkVersion" }
crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreport" }
kyant0-capsule = { module = "io.github.kyant0:capsule", version.ref = "kyant0Capsule" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
